name: tieba

on:
  workflow_dispatch:
  schedule:
    - cron: "50 5 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 14
        uses: actions/setup-node@v4
        with:
          node-version: '14.x'

      - name: Cache node_modules
        uses: actions/cache@v3
        id: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ matrix.node-version }}-nodeModules-${{ hashFiles('package-lock.json') }}-${{ hashFiles('package.json') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.node-version }}-nodeModules-

      - name: Install dependency packages
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: |
          npm install

      - name: Start running the script
        run: |
          node src/web/sudojia_tieba.js
        env:
          TIE_BA_COOKIE: ${{ secrets.TIE_BA_COOKIE }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_USER_ID: ${{ secrets.TG_USER_ID }}
          PUSH_KEY: ${{ secrets.PUSH_KEY }}
          BARK_PUSH: ${{ secrets.BARK_PUSH }}
          BARK_SOUND: ${{ secrets.BARK_SOUND }}
          DD_BOT_TOKEN: ${{ secrets.DD_BOT_TOKEN }}
          DD_BOT_SECRET: ${{ secrets.DD_BOT_SECRET }}
          QYWX_KEY: ${{ secrets.QYWX_KEY }}
          IGOT_PUSH_KEY: ${{ secrets.IGOT_PUSH_KEY }}
          PUSH_PLUS_TOKEN: ${{ secrets.PUSH_PLUS_TOKEN }}
          PUSH_PLUS_USER: ${{ secrets.PUSH_PLUS_USER }}

      - name: Delete Workflow Runs
        uses: Mattraks/delete-workflow-runs@main
        with:
          retain_days: 1
          keep_minimum_runs: 1
